import food1 from "../assets/food1.jpg";

export const foodTravel = [
  {
    title: "홍콩반점",
    image: food1,
    rating: 4.5,
    address: "서울 관악구",
    menu: "짬뽕",
    price: "₩6,000",
    items: ["짬뽕 - 6,000원", "볶음밥 - 5,500원", "탕수육 (소) - 9,000원"],
  },
  {
    title: "삼청동 카레집",
    image: food1,
    rating: 4.3,
    address: "서울 종로구",
    menu: "치킨카레",
    price: "₩7,500",
    items: ["치킨카레 - 7,500원", "야채카레 - 6,500원"],
  },
  {
    title: "빠리버거",
    image: food1,
    rating: 4.6,
    address: "서울 마포구",
    menu: "치즈버거 세트",
    price: "₩5,900",
    items: ["치즈버거 세트 - 6,900원", "불고기버거 단품 - 4,800원"],
  },
  {
    title: "멘야고코로",
    image: food1,
    rating: 4.8,
    address: "서울 양천구",
    menu: "소유라멘",
    price: "₩7,500",
    items: ["소유라멘 - 7,500원", "미소라멘 - 7,900원"],
  },
  {
    title: "김밥천국",
    image: food1,
    rating: 4.2,
    address: "서울 마포구",
    menu: "돈가스 김밥",
    price: "₩5,000",
    items: ["참치김밥 - 4,500원", "라볶이 - 7,000원"],
  },
  {
    title: "또래오래",
    image: food1,
    items: ["순살 치킨 한 조각 - 1,800원", "치킨마요덮밥 - 5,900원"],
  },
  {
    title: "명동우동",
    image: food1,
    items: ["우동 - 4,500원", "모듬튀김 - 3,000원"],
  },
  {
    title: "바르다김선생",
    image: food1,
    items: ["제육김밥 - 6,000원", "육개장컵밥 - 7,800원"],
  },
];

export const topRestaurants = [
  {
    id: 1,
    name: "압구정 김밥천국",
    image: food1,
    menu: "김밥 세트",
    price: "₩5,000",
    rating: "4.9",
    address: "서울 강남구 압구정로",
  },
  {
    id: 2,
    name: "해운대 분식",
    image: food1,
    menu: "떡볶이",
    price: "₩6,000",
    rating: "4.8",
    address: "부산 해운대구",
  },
  {
    id: 3,
    name: "제주 삼다김밥",
    image: food1,
    menu: "김밥",
    price: "₩4,500",
    rating: "4.7",
    address: "제주 제주시",
  },
];

export const regions = [
  "서울",
  "경기",
  "강원",
  "전라",
  "부산",
  "경상",
  "충청",
  "제주",
];

export const restaurantData = {
  서울: [
    {
      id: 101,
      name: "강남 즉석 떡볶이",
      image: food1,
      menu: "떡볶이",
      price: "₩7,500",
      rating: "4.8",
      address: "서울 강남구",
    },
    {
      id: 102,
      name: "홍대 김밥나라",
      image: food1,
      menu: "김밥+라면 세트",
      price: "₩8,000",
      rating: "4.6",
      address: "서울 마포구",
    },
  ],
  경기: [
    {
      id: 201,
      name: "수원 떡볶이집",
      image: food1,
      menu: "떡볶이",
      price: "₩6,500",
      rating: "4.7",
      address: "경기 수원시",
    },
    {
      id: 202,
      name: "일산 순대국집",
      image: food1,
      menu: "순대국",
      price: "₩7,000",
      rating: "4.5",
      address: "경기 고양시",
    },
  ],
  강원: [
    {
      id: 301,
      name: "강릉 커피거리",
      image: food1,
      menu: "아메리카노",
      price: "₩5,000",
      rating: "4.6",
      address: "강원 강릉시",
    },
    {
      id: 302,
      name: "춘천 닭갈비집",
      image: food1,
      menu: "닭갈비",
      price: "₩8,500",
      rating: "4.8",
      address: "강원 춘천시",
    },
  ],
  전라: [
    {
      id: 401,
      name: "전주 비빔밥집",
      image: food1,
      menu: "비빔밥",
      price: "₩7,000",
      rating: "4.7",
      address: "전라 전주시",
    },
    {
      id: 402,
      name: "광주 떡갈비 분식",
      image: food1,
      menu: "떡갈비덮밥",
      price: "₩9,800",
      rating: "4.7",
      address: "광주 광산구",
    },
  ],
  부산: [
    {
      id: 501,
      name: "광안리 분식집",
      image: food1,
      menu: "튀김 모듬",
      price: "₩9,000",
      rating: "4.7",
      address: "부산 수영구",
    },
    {
      id: 502,
      name: "서면 컵밥 맛집",
      image: food1,
      menu: "컵밥",
      price: "₩6,500",
      rating: "4.5",
      address: "부산 부산진구",
    },
  ],
  경상: [
    {
      id: 601,
      name: "경산 떡볶이",
      image: food1,
      menu: "떡볶이",
      price: "₩6,200",
      rating: "4.5",
      address: "경상 경산시",
    },
    {
      id: 602,
      name: "포항 회덮밥",
      image: food1,
      menu: "회덮밥",
      price: "₩9,800",
      rating: "4.6",
      address: "경상 포항시",
    },
  ],
  충청: [
    {
      id: 701,
      name: "대전 카페거리",
      image: food1,
      menu: "커피+케이크 세트",
      price: "₩8,500",
      rating: "4.7",
      address: "충청 대전시",
    },
    {
      id: 702,
      name: "천안 순대국",
      image: food1,
      menu: "순대국",
      price: "₩7,000",
      rating: "4.5",
      address: "충청 천안시",
    },
  ],
  제주: [
    {
      id: 801,
      name: "제주 흑돼지 덮밥",
      image: food1,
      menu: "흑돼지덮밥",
      price: "₩8,900",
      rating: "4.9",
      address: "제주 서귀포시",
    },
    {
      id: 802,
      name: "애월 카페거리",
      image: food1,
      menu: "아메리카노+빵 세트",
      price: "₩6,500",
      rating: "4.6",
      address: "제주 애월읍",
    },
  ],
};
